flux_map = {
            1:'Time_Sim_production_rate_k',
            2:'MAb_PCSK9_kel',
            3:'MAb_PCSK9_association_rate_k',
            4:'MAb_PCSK9_association_rate_k*MAb_PCSK9_Kd',
            5:'MAb_kel',
            6:'Statin_Ka',
            7:'Statin_Ka*Statin_F',
            8:'Statin_kel',
            9:'LDLR_ic_P_production_rate_k',
            10:'LDLR_ic_to_cs_P_trafficking_rate_k',
            11:'SREBP_ic_P_production_rate_k',
            12:'SREBP_ic_P_degradation_rate_k',
            13:'SREBP_ic_to_nu_P_activation_rate_k',
            14:'LDLR_P_internalization_rate_k',
            15:'LDLR_P_recycling_rate_k',
            16:'LDL_LDLR_pl_association_rate_k',
            17:'LDL_LDLR_pl_association_rate_k*LDL_LDLR_pl_Kd',
            18:'PCSK9_LDLR_pl_association_rate_k',
            19:'PCSK9_LDLR_pl_association_rate_k*PCSK9_LDLR_pl_Kd',
            20:'LDL_LDLR_en_association_rate_k',
            21:'LDL_LDLR_en_association_rate_k*LDL_LDLR_en_Kd',
            22:'PCSK9_LDLR_en_association_rate_k',
            23:'PCSK9_LDLR_en_association_rate_k*PCSK9_LDLR_en_Kd',
            24:'LDLR_en_P_degradation_rate_k',
            25:'PCSK9_en_P_degradation_rate_k',
            26:'LDL_LDLR_P_internalization_rate_k',
            27:'PC9_LDLR_P_internalization_rate_k',
            28:'ApoB_pl_clearance_rate_k',
            29:'ApoA1_pl_clearance_rate_k',
            30:'PCSK9_pl_clearance_rate_k',
            31:'Statin_Ka*(1-Statin_F)',
            32:'MAb_Ka',
            33:'MAb_Ka*MAb_F',
            34:'MAb_Ka*(1-MAb_F)',
            35:'PC9_LDLR_en_P_degradation_rate_k',
            36:'Chol_ic_P_production_rate_k',
            37:'Chol_ic_P_elimination_rate_k',
            38:'SREBP_nu_P_degradation_rate_k',
            39:'LDL_en_to_Chol_ic_P_rate_k',
            40:'VLDL_to_LDL_conversion_rate_k',
            41:'HDL_to_LDL_exchange_rate_k',
            42:'Chol_ic_P_to_HDL_pl_rate_k',
            43:'VLDL_pl_P_uptake_rate_k',
            44:'HDL_to_VLDL_exchange_rate_k',
            45:'LDL_pl_LDLRind_P_uptake_rate_k',
            46:'MAb_PC9_2_kel',
            47:'MAb_PC9_2_association_rate_k',
            48:'MAb_PC9_2_association_rate_k*MAb_PC9_2_Kd',
            49:'0',
            50:'0',
            51:'PCSK9_pl_P_uptake_rate_k',
            52:'Statin_kmet',
            53:'Statin_pl_to_pc_rate_k',
            54:'Statin_pc_to_pl_rate_k',
            55:'StatinM_kel',
            56:'VLDL_pl_P_LDLRuptake_rate_k'}

metabolite_map = {
            1 :  'Statin_pl',
            2 :  'Time_Sim',
            3 :  'PCSK9_pl',
            4 :  'MAb_PCSK9_pl',
            5 :  'MAb_pl',
            6 :  'Statin_gi',
            7 :  'VLDL_pl',
            8 :  'HDL_pl',
            9 :  'ApoA1_pl',
            10 : 'Chol_ic_P',
            11 : 'ApoB_pl',
            12 : 'LDLR_cs_P',
            13 : 'LDL_LDLR_cs_P',
            14 : 'LDL_LDLR_en_P',
            15 : 'LDLR_en_P',
            16 : 'LDLR_ic_P',
            17 : 'PC9_LDLR_cs_P',
            18 : 'PC9_LDLR_en_P',
            19 : 'PCSK9_en_P',
            20 : 'LDL_en_P',
            21 : 'SREBP_ic_P',
            22 : 'SREBP_nu_P',
            23 : 'MAb_sc',
            24 : 'MAb_PC9_2_pl',
            25 : 'LDL_pl',
            26 : 'StatinM_pl',
            27 : 'Statin_pc',
            28 : 'CETP_pl',
}

volume_map = {
    1 : 'volume_pl',
    2 : 'volume_P',
    3 : 'volume_en_P'
}

k_map = {
1 : 'chol_per_HDL_particle',
2 : 'chol_per_VLDL_particle',
3 : 'chol_per_LDL_particle',
}

p_map ={

    1 : 'ApoA1_RCT_EC50',
    2 : 'ApoA1_RCT_nh',
    3 : 'ApoB_HDL_LDL_EC50',
    4 : 'ApoB_HDL_LDL_nh',
    5 : 'ApoB_HDL_VLDL_EC50',
    6 : 'ApoB_HDL_VLDL_nh',
    7 : 'CETP_HDL_LDL_EC50',
    8 : 'CETP_HDL_LDL_nh',
    9 : 'CETP_HDL_VLDL_EC50',
    10 :'CETP_HDL_VLDL_nh',
    11 :'Chol_er_exp',
    12 :'Chol_er_P_base',
    13 :'Chol_ic_P_base',
    14 :'Chol_SREBP_Imax',
    15 :'Chol_SREBP_nh',
    16 :'Fibrate_LPL_EC50',
    17 :'Fibrate_LPL_Emax',
    18 :'Fibrate_LPL_nh',
    19 :'LDLR_internalization_fraction_P',
    20 :'SREBP_Chol_EC50',
    21 :'SREBP_Chol_nh',
    22 :'SREBP_LDLR_EC50',
    23 :'SREBP_LDLR_nh',
    24 :'Statin_Chol_Imax',
    25 :'Statin_Chol_nh',
    26 :'Statin_Chol_P_IC50',
    27 :'weight_ApoB_HDL_LDL',
    28 :'weight_ApoB_HDL_VLDL',
    29 :'weight_CETP_HDL_LDL',
    30 :'weight_CETP_HDL_VLDL',
    31 :'convert_nM_to_uM',
    32 :'Statin_Vd',
    33 :'StatinM_Vd',
    34 :'MAb_Vd',
    35 :'Chol_er_P',
}

c_map = {
      1 : 'Conc_Statin',
      2 : 'Conc_Fibrate'
}

maps = [flux_map, metabolite_map, volume_map, p_map, k_map, c_map]