%% Fluxes =sym(' 
f = sym('f', [63 1]);
     f(1) =sym('Time_Sim_production_rate_k');
     f(2) =sym('MAb_PCSK9_kel'); 
     f(3) =sym('MAb_PCSK9_association_rate_k');
     f(4) =sym('MAb_PCSK9_association_rate_k*MAb_PCSK9_Kd');
     f(5) =sym('MAb_kel');
     f(6) =sym('Statin_Ka');
     f(7) =sym('Statin_Ka*Statin_F');
     f(8) =sym('Statin_kel'); 
     f(9) =sym('LDLR_ic_P_production_rate_k');
     f(10) =sym('LDLR_ic_to_cs_P_trafficking_rate_k');
     f(11) =sym('SREBP_ic_P_production_rate_k');
     f(12) =sym('SREBP_ic_P_degradation_rate_k');
     f(13) =sym('SREBP_ic_to_nu_P_activation_rate_k');
     f(14) =sym('LDLR_P_internalization_rate_k');
     f(15) =sym('LDLR_P_recycling_rate_k');
     f(16) =sym('LDL_LDLR_pl_association_rate_k');
     f(17) =sym('LDL_LDLR_pl_association_rate_k*LDL_LDLR_pl_Kd');
     f(18) =sym('PCSK9_LDLR_pl_association_rate_k');
     f(19) =sym('PCSK9_LDLR_pl_association_rate_k*PCSK9_LDLR_pl_Kd');
     f(20) =sym('LDL_LDLR_en_association_rate_k');
     f(21) =sym('LDL_LDLR_en_association_rate_k*LDL_LDLR_en_Kd');
     f(22) =sym('PCSK9_LDLR_en_association_rate_k');
     f(23) =sym('PCSK9_LDLR_en_association_rate_k*PCSK9_LDLR_en_Kd');
     f(24) =sym('LDLR_en_P_degradation_rate_k');
     f(25) =sym('PCSK9_en_P_degradation_rate_k');
     f(26) =sym('LDL_LDLR_P_internalization_rate_k');
     f(27) =sym('PC9_LDLR_P_internalization_rate_k');
     f(28) =sym('ApoB_pl_clearance_rate_k');
     f(29) =sym('ApoA1_pl_clearance_rate_k');
     f(30) =sym('PCSK9_pl_clearance_rate_k');
     f(31) =sym('Statin_Ka*(1-Statin_F)');
     f(32) =sym('MAb_Ka');
     f(33) =sym('MAb_Ka*MAb_F');
     f(34) =sym('MAb_Ka*(1-MAb_F)');
     f(35) =sym('PC9_LDLR_en_P_degradation_rate_k');
     f(36) =sym('Chol_ic_P_production_rate_k');
     f(37) =sym('Chol_ic_P_elimination_rate_k');
     f(38) =sym('SREBP_nu_P_degradation_rate_k');
     f(39) =sym('LDL_en_to_Chol_ic_P_rate_k');
     f(40) =sym('VLDL_to_LDL_conversion_rate_k');
     f(41) =sym('HDL_to_LDL_exchange_rate_k');
     f(42) =sym('Chol_ic_P_to_HDL_pl_rate_k');
     f(43) =sym('VLDL_pl_P_uptake_rate_k');
     f(44) =sym('HDL_to_VLDL_exchange_rate_k');
     f(45) =sym('LDL_pl_LDLRind_P_uptake_rate_k');
     f(46) =sym('MAb_PC9_2_kel');
     f(47) =sym('MAb_PC9_2_association_rate_k');
     f(48) =sym('MAb_PC9_2_association_rate_k*MAb_PC9_2_Kd');
     f(49) =sym('0');
     f(50) =sym('0');
     f(51) =sym('PCSK9_pl_P_uptake_rate_k');
     f(52) =sym('Statin_kmet');
     f(53) =sym('Statin_pl_to_pc_rate_k');
     f(54) =sym('Statin_pc_to_pl_rate_k');
     f(55) =sym('StatinM_kel');
     f(56) =sym('VLDL_pl_P_LDLRuptake_rate_k');
 
%% v = 
v = sym('v', [3 1]);
v(1) = sym('volume_pl');
v(2) = sym('volume_P');
v(3) = sym('volume_en_P');
 
%% k = 
k = sym('k', [3 1]);
k(1) = sym('chol_per_HDL_particle');
k(2) = sym('chol_per_VLDL_particle');
k(3) = sym('chol_per_LDL_particle');
 
%% p = 
p = sym('p', [35 1]);
p(1)    =sym('ApoA1_RCT_EC50'); 
p(2)    =sym('ApoA1_RCT_nh');
p(3)    =sym('ApoB_HDL_LDL_EC50');
p(4)    =sym('ApoB_HDL_LDL_nh');    
p(5)    =sym('ApoB_HDL_VLDL_EC50'); 
p(6)    =sym('ApoB_HDL_VLDL_nh');   
p(7)    =sym('CETP_HDL_LDL_EC50');  
p(8)    =sym('CETP_HDL_LDL_nh');    
p(9)    =sym('CETP_HDL_VLDL_EC50'); 
p(10)   =sym('CETP_HDL_VLDL_nh');   
p(11)   =sym('Chol_er_exp');    
p(12)   =sym('Chol_er_P_base');     
p(13)   =sym('Chol_ic_P_base'); 
p(14)   =sym('Chol_SREBP_Imax');    
p(15)   =sym('Chol_SREBP_nh');  
p(16)   =sym('Fibrate_LPL_EC50');   
p(17)   =sym('Fibrate_LPL_Emax');   
p(18)   =sym('Fibrate_LPL_nh'); 
p(19)   =sym('LDLR_internalization_fraction_P');
p(20)   =sym('SREBP_Chol_EC50');    
p(21)   =sym('SREBP_Chol_nh');  
p(22)   =sym('SREBP_LDLR_EC50');    
p(23)   =sym('SREBP_LDLR_nh');  
p(24)   =sym('Statin_Chol_Imax');   
p(25)   =sym('Statin_Chol_nh'); 
p(26)   =sym('Statin_Chol_P_IC50'); 
p(27)   =sym('weight_ApoB_HDL_LDL');    
p(28)   =sym('weight_ApoB_HDL_VLDL');   
p(29)   =sym('weight_CETP_HDL_LDL');    
p(30)   =sym('weight_CETP_HDL_VLDL');
p(31)   =sym('convert_nM_to_uM');
p(32)   =sym('Statin_Vd');
p(33)   =sym('StatinM_Vd');
p(34)   =sym('MAb_Vd');
p(35)   =sym('Chol_er_P');

%% c = 
c = sym('c', [3 1]);
c(1) = sym('Conc_Statin');
c(2) = sym('Conc_Fibrate');
% convert_nM_to_uM*(Statin_pl/Statin_Vd+StatinM_pl/StatinM_Vd) = Conc_Statin
% convert_nM_to_uM*(Ezet_pl/Ezet_Vd+Ezet_gluc_pl/Ezet_gluc_Vd) = Conc_Ezet
% convert_nM_to_uM*Fibrate_pl/Fibrate_Vd = Conc_Fibrate
% Chol_er_H_base*power(exp((Chol_ic_H-Chol_ic_H_base)/Chol_ic_H_base),Chol_er_exp) = Chol_er_H
% Chol_er_P_base*power(exp((Chol_ic_P-Chol_ic_P_base)/Chol_ic_P_base),Chol_er_exp) = Chol_er_P
